### ISSUE TITLE
FPE masking/float precision

### ISSUE THREAD

**Issue by aehrath-gretel** [gretelai/gretel-python-client#20]
So in talking with John, I think we need to solve some issues:
1. currently we can specify float_precision as "only encrypt, n decimal places beyond the decimal point" so that lat-lon's can preserve basic features depending on n.
For example:
lat 172.12345 with precision = 2 
may yield: 172.12**975643** 
But, if the incoming value is of type string, it does not get treated like a float.
To solve this, I am thinking, if float_precision is NOT None, then it is assumed that the data values are floats, and if the incoming value is of type float, it will do what it currently does, if it is of type string, then we figure out where the decimal point is in the string, and work out which digits we need to encrypt from there. So, for the above example as a string we would get:
"172.12345" -> "172.12**975**" notice how the number of digits behind the decimal does not need to change in this example, as we do not need to take extra care of outputting a native float value. 
2. Make mask and float precision mutually exclusive. Given point 1., it would no longer make sense to specify both, a mask and a float precision, as it would not be clear which one of the 2 should be applied.
We still need a way to specify masks for things like credit card numbers where we might want to preserve the first digit to retain which credit card was used, or even the first 6 digits to retain which bank the credit card belongs to.
3. I have been thinking about expressing precision in a form closer to sci notation in powers of 10. That way we could specify precision for the integer part as well.

**Comment by johntmyers** [comment]
Per discussion:this currently feels like having dedicated `FloatFPE` and `StringFPE` sub-classed configs should be used. This way we don't have too much business logic for the user to think about in a single class. It also helps them more cleanly choose what functionality they want purely by choosing one of the specific subclasses to use.

Since we already have floating number support, we can start with that one
