### ISSUE TITLE
Unable to upload in UI

### ISSUE THREAD

**Issue by Satishkumar44** [gretelai/gretel-python-client#55]
When iam trying to upload to UI using import option for a csv file it is giving your file is being uploaded and below it another message stating that couldnot upload only json and csv are to be uploaded

**Comment by johntmyers** [comment]
@Satishkumar44 thanks for your feedback. What kind of file are you trying to upload? Can you share any sample data?

**Comment by johntmyers** [comment]
@Satishkumar44 I am closing this issue since we did not get a response. Please feel free to re-open or start a new one. Any specific actions / sample data that reproduce the issue would be helpful too, thanks!
