### ISSUE TITLE
Gpu Requirement for Ubuntu 

### ISSUE THREAD

**Issue by PoojaSri-E** [gretelai/gretel-python-client#72]
Is GPU mandatory for Ubuntu with the AWS to run gretel locally?

Whether we can run AWS without the GPU, like using normal CPU with Ubuntu?

**Comment by mckornfield** [comment]
@PoojaSri-E I don't believe the GPU is mandatory, but for some of our model types, it won't run very quickly or successfully. Which models were you planning on running?

**Comment by mckornfield** [comment]
Closing as stale
