### ISSUE TITLE
Build wheel error on windows

### ISSUE THREAD

**Issue by PoojaSri-E** [gretelai/gretel-python-client#73]
Getting build wheel error while installing gretel client, running locally in windows 11.
Is it possible to run gretel client locally in windows?
OS: windows 11
Python version : 3.11.3

![Screenshot (44)](https://user-images.githubusercontent.com/89568454/235654471-63ea62c6-b691-4654-a081-62ed7b823be2.png)
![Screenshot (43)](https://user-images.githubusercontent.com/89568454/235654476-3388f6f2-9213-450f-92a7-22d583dfa0b5.png)

**Comment by pimlock** [comment]
Hi @PoojaSri-E, it looks like this error may be caused by `setuptools` package in your Python installation being out of date.

Could you please try upgrading `setuptools` by running (`pip install setuptools -U`) and trying to run `pip install gretel-client` again?

**Comment by mckornfield** [comment]
Closing as stale
